name: Upload Calls to BigQuery

on:
  schedule:
    - cron: '1 0 * * *'  # Запуск в 00:01 UTC

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: pip install google-cloud-bigquery requests pandas

      - name: Run Script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        run: python upload_calls.py
