name: Upload Calls to BigQuery

on:
  schedule:
    - cron: "0 3 * * *"  # Запуск каждый день в 03:00 UTC (6:00 MSK)
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  upload_calls:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Checkout репозиторий
        uses: actions/checkout@v3

      - name: 🔧 Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: 📦 Установка зависимостей
        run: pip install google-cloud-bigquery pandas requests

      - name: 🔄 Запуск скрипта загрузки звонков
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          UIS_ACCESS_TOKEN: ${{ secrets.UIS_ACCESS_TOKEN }}
          BQ_PROJECT_ID: ${{ secrets.BQ_PROJECT_ID }}
          BQ_DATASET_ID: ${{ secrets.BQ_DATASET_ID }}
        run: python upload_calls.py
