name: Upload Calls to BigQuery

on:
  schedule:
    - cron: "0 2 * * *"  # Запуск каждый день в 02:00 UTC
  workflow_dispatch:  # Запуск вручную

jobs:
  upload_calls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v3

      - name: Установка зависимостей
        run: pip install google-cloud-bigquery pandas requests

      - name: Проверяем секреты
        run: |
          if [ -z "${{ secrets.GCP_SERVICE_ACCOUNT }}" ]; then
            echo "❌ Ошибка: GCP_SERVICE_ACCOUNT отсутствует!"
            exit 1
          else
            echo "✅ GCP_SERVICE_ACCOUNT найден."
          fi
          if [ -z "${{ secrets.UIS_ACCESS_TOKEN }}" ]; then
            echo "❌ Ошибка: UIS_ACCESS_TOKEN отсутствует!"
            exit 1
          else
            echo "✅ UIS_ACCESS_TOKEN найден."
          fi

      - name: Запуск скрипта
        env:
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          UIS_ACCESS_TOKEN: ${{ secrets.UIS_ACCESS_TOKEN }}
          BQ_PROJECT_ID: "your-gcp-project-id"
          BQ_DATASET_ID: "your_dataset"
        run: python upload_calls.py
